# Generated by Django 4.1.3 on 2022-11-28 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['exercise_name']},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
