# Generated by Django 4.1.3 on 2022-11-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_exercise_options_alter_workout_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['workout_name']},
        ),
    ]
