# Generated by Django 4.1.3 on 2022-11-28 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_workout_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='user',
            name='workout',
        ),
        migrations.AddField(
            model_name='user',
            name='exercises',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.exercise'),
        ),
        migrations.AddField(
            model_name='user',
            name='workouts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.workout'),
        ),
    ]
