# Generated by Django 4.1.3 on 2022-11-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_remove_user_exercises_remove_user_workouts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name']},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Lastname',
            new_name='last_name',
        ),
    ]
